feat(shields): Add Fifi Shield Support
zmkfirmware/zmk pull request #1008
Opened 2021-10-31 18:08 UTC by hmngwy

## Board/Shield Check-list
 - [x] This board/shield is tested working on real hardware
 - [x] Definitions follow the general style of other shields/boards upstream ([Reference](https://zmk.dev/docs/development/new-shield))
 - [x] `.zmk.yml` metadata file added
 - [x] Proper Copyright + License headers added to applicable files (Generally, we stick to "The ZMK Contributors" for copyrights to help avoid churn when files get edited)
 - [x] General consistent formatting of DeviceTree files
 - [ ] Keymaps do not use deprecated key defines (Check using the [upgrader tool](https://zmk.dev/docs/codes/keymap-upgrader))
 - [x] `&pro_micro` used in favor of `&pro_micro_d/a` if applicable
 - [x] If split, no name added for the right/peripheral half
 - [x] `.conf` file has optional extra features commented out

2021-11-28 20:28 UTC, Nicell requested changes

2021-11-28 20:28 UTC, Nicell commented on .github/workflows/build.yml
> +          - fifi_right
Please don't edit this file for now. We're working on removing this file in favor of a dynamic build script that doesn't require explicit builds.

2021-11-28 20:28 UTC, Nicell commented on app/boards/shields/fifi/Kconfig.defconfig
> +if SHIELD_FIFI_LEFT
Missing copyright header

2021-11-28 20:28 UTC, Nicell commented on app/boards/shields/fifi/Kconfig.shield
> +# Copyright (c) 2020 Pete Johanson
```suggestion
# Copyright (c) 2021 The ZMK Contributors
```

2021-11-28 20:28 UTC, Nicell commented on app/boards/shields/fifi/fifi.dtsi
> + * Copyright (c) 2020 The ZMK Contributors
```suggestion
 * Copyright (c) 2021 The ZMK Contributors
```

2021-11-28 20:28 UTC, Nicell commented on app/boards/shields/fifi/fifi.dtsi
> +	// TODO: drop-lighting RGB node(s)?
```suggestion
```
This is handled by the spi  overlay

2021-11-28 20:28 UTC, Nicell commented on app/boards/shields/fifi/fifi.keymap
> + * Copyright (c) 2020 The ZMK Contributors
```suggestion
 * Copyright (c) 2021 The ZMK Contributors
```

2021-11-28 20:28 UTC, Nicell commented on app/boards/shields/fifi/fifi_left.overlay
> + * Copyright (c) 2020 Pete Johanson
```suggestion
 * Copyright (c) 2021 The ZMK Contributors
```

2021-11-28 20:28 UTC, Nicell commented on app/boards/shields/fifi/fifi_right.overlay
> + * Copyright (c) 2020 Pete Johanson
```suggestion
 * Copyright (c) 2021 The ZMK Contributors
```

2022-02-22 03:48 UTC, hmngwy commented
@Nicell added the missing copyright lines, updated to 2022, ditched the changes to build.yml

2022-03-14 05:56 UTC, Nicell requested changes
Please remove the `fifi_left.conf` and `fifi_right.conf` files! Otherwise I think this definition looks good. Thanks. You can re-request my review after updating.

2022-10-25 03:56 UTC, petejohanson commented
@hmngwy Please feel free to re-open this once you have a chance to address the item from @Nicell and this is ready for review again.

Thanks!

2022-10-25 03:56 UTC, closed without merging

2023-02-21 16:33 UTC, hmngwy commented
Hi @petejohanson, rebased with main and then reapplied my changes, but I'm getting the below:

```
FATAL ERROR: command exited with status 1: /usr/local/bin/cmake -DWEST_PYTHON=/usr/bin/python3 -B/__w/zmk/zmk/build -S/__w/zmk/zmk/app -GNinja -DBOARD=nice_nano -DSHIELD=fifi
Error: Failed to build or upload nice_nano fifi undefined
```

https://github.com/hmngwy/zmk/actions/runs/4234720633/jobs/7357427250#step:10:140

I'm not quite sure what I'm doing wrong, I checked the New Keyboard Shields guide as well if anything there is new since I slept on this PR, and it seems what I added here seems to still comply, however the error says otherwise and I can't tell what I'm missing.

If you're not too busy, a quick look would be appreciated. Thanks!

2023-02-21 16:45 UTC, caksoylar commented
@hmngwy You should be building with `fifi_left` and `fifi_right` shields separately, right?