feat(shield) Add Chalice support
zmkfirmware/zmk pull request #1022
Opened 2021-11-10 11:27 UTC by joshajohnson

Adding support for [Chalice](https://customkbd.com/products/chalice-pre-order).
This is my first ZMK PR so apologies for any issues and thanks in advance :)

## Board/Shield Check-list
 - [X] This board/shield is tested working on real hardware
 - [X] Definitions follow the general style of other shields/boards upstream ([Reference](https://zmk.dev/docs/development/new-shield))
 - [X] `.zmk.yml` metadata file added
 - [X] Proper Copyright + License headers added to applicable files (Generally, we stick to "The ZMK Contributors" for copyrights to help avoid churn when files get edited)
 - [X] General consistent formatting of DeviceTree files
 - [X] Keymaps do not use deprecated key defines (Check using the [upgrader tool](https://zmk.dev/docs/codes/keymap-upgrader))
 - [X] `&pro_micro` used in favor of `&pro_micro_d/a` if applicable
 - [X] If split, no name added for the right/peripheral half
 - [X] `.conf` file has optional extra features commented out

2021-11-28 20:44 UTC, Nicell requested changes
Generally looks great, one small change, and then I was curious when this shield will start to ship, as we'd like to wait until then to merge it in.

2021-11-28 20:44 UTC, Nicell commented on app/boards/shields/chalice/chalice.zmk.yml
> +  - keys
```suggestion
  - keys
  - underglow
```

2021-11-29 08:18 UTC, joshajohnson commented
Thanks for the review @Nicell 😄

Chalice is currently shipping, so if it's possible to merge now that would be great.
We caught the split backspace issue in the field from one of the early units.

2021-11-29 16:12 UTC, Nicell approved these changes

2021-11-29 17:39 UTC, merged