Initial commit of boardsource5x12
zmkfirmware/zmk pull request #1027
Opened 2021-11-19 17:08 UTC by fsargent

## Board/Shield Check-list
 - [X] This board/shield is tested working on real hardware
 - [X] Definitions follow the general style of other shields/boards upstream ([Reference](https://zmk.dev/docs/development/new-shield))
 - [X] `.zmk.yml` metadata file added
 - [X] Proper Copyright + License headers added to applicable files (Generally, we stick to "The ZMK Contributors" for copyrights to help avoid churn when files get edited)
 - [X] General consistent formatting of DeviceTree files
 - [X] Keymaps do not use deprecated key defines (Check using the [upgrader tool](https://zmk.dev/docs/codes/keymap-upgrader))
 - [X] `&pro_micro` used in favor of `&pro_micro_d/a` if applicable
 - [X] If split, no name added for the right/peripheral half
 - [X] `.conf` file has optional extra features commented out

2021-11-23 00:08 UTC, petejohanson requested changes
A few minor things.

2021-11-23 00:08 UTC, petejohanson commented on app/boards/shields/boardsource5x12/Kconfig.defconfig
> +# Copyright (c) 2020 The ZMK Contributors
Should be 2021:

```suggestion
# Copyright (c) 2021 The ZMK Contributors
```

2021-11-23 00:08 UTC, petejohanson commented on app/boards/shields/boardsource5x12/Kconfig.shield
> +# Copyright (c) 2020 The ZMK Contributors
```suggestion
# Copyright (c) 2021 The ZMK Contributors
```

2021-11-23 00:08 UTC, petejohanson commented on app/boards/shields/boardsource5x12/boardsource5x12.keymap
> + * Copyright (c) 2020 The ZMK Contributors
```suggestion
 * Copyright (c) 2021 The ZMK Contributors
```

2021-11-23 00:08 UTC, petejohanson commented on app/boards/shields/boardsource5x12/boardsource5x12.overlay
> + * Copyright (c) 2020 The ZMK Contributors
```suggestion
 * Copyright (c) 2021 The ZMK Contributors
```

2021-11-23 00:13 UTC, fsargent commented
Done

2021-11-24 02:35 UTC, petejohanson requested changes
A few more items I missed on the first pass. Thanks!

2021-11-24 02:35 UTC, petejohanson commented on app/boards/shields/boardsource5x12/boardsource5x12.keymap
> +        RAISE {
These should be lowercase and using the convention:

```suggestion
        raise_layer {
```

2021-11-24 02:35 UTC, petejohanson commented on app/boards/shields/boardsource5x12/boardsource5x12.keymap
> +        LOWER {
```suggestion
        lower_layer {
```

2021-11-24 02:35 UTC, petejohanson commented on app/boards/shields/boardsource5x12/boardsource5x12.keymap
> +                &kp ESC    &kp F1       &kp F2   &kp F3    &kp F4    &kp F5      &kp F6    &kp F7    &kp F8    &kp F9   &kp F10  &kp F11
We usually aim to have the `&bt` behaviors bound somewhere in the default keymap somewhere too.

2021-11-29 23:01 UTC, fsargent commented
Ready for re-review

2021-12-13 17:55 UTC, Nicell reviewed
Just one change left from what I can see 😄

2021-12-13 17:55 UTC, Nicell commented on app/boards/shields/boardsource5x12/boardsource5x12.keymap
> +        lower {
```suggestion
        lower_layer {
```
These layers should follow suit with the `default_layer`

2021-12-13 18:42 UTC, fsargent commented
Resolved @Nicell

2021-12-13 18:44 UTC, Nicell commented
Hey @fsargent, there's still the rest of the layers after `lower_layer` that needs `_layer` added 😄

2021-12-13 19:07 UTC, fsargent commented
Sorry, done!

2021-12-13 19:09 UTC, Nicell approved these changes

2021-12-13 19:14 UTC, fsargent commented
🎉

2021-12-13 20:24 UTC, merged