feat(behaviors): Add option for tapdance to output on each key press
zmkfirmware/zmk pull request #1313
Opened 2022-05-21 07:44 UTC by nickconway

Adds the option for a tap-dance to output each bind on key press similar to QMK's on_each_tap_fn.

2022-06-15 05:32 UTC, petejohanson requested changes
One naming suggestion. Also, need to add tests for this configuration and various edge cases around it too, please.

2022-06-15 05:32 UTC, petejohanson commented on app/dts/bindings/behaviors/zmk,behavior-tap-dance.yaml
> +  on-each-press:
Not sure I love this naming... Brainstorming other ideas:

* `trigger-each-binding`
* `tap-every-binding`
* `tap-each`

Thoughts?

2022-06-15 23:27 UTC, kurtis-lew commented
Thought I'd weigh in here. The `each` keyword sounds the most correct for this application since the word,`every`, could be interpreted that it invokes all keybinds at once, or at least that's my personal reaction.

Some other suggestions:
- `activate-each-binding`
- `invoke-each-binding`
- `timerless`/`disable-tapping-term`
  - From what I understand, this boolean value makes tap-dances activate their bindings independent from their - `tapping-term-ms`. We could even just make it so if `tapping-term-ms == -1`, then this feature is enabled.

2022-06-16 00:06 UTC, nickconway commented
> Thought I'd weigh in here. The `each` keyword sounds the most correct for this application since the word,`every`, could be interpreted that it invokes all keybinds at once, or at least that's my personal reaction.
> 
> Some other suggestions:
> 
> * `activate-each-binding`
> * `invoke-each-binding`
> * `timerless`/`disable-tapping-term`
>   
>   * From what I understand, this boolean value makes tap-dances activate their bindings independent from their  `tapping-term-ms`. We could even just make it so if `tapping-term-ms == -1`, then this feature is enabled.

I think I like 'activate-each-binding' the best. This still uses the tapping term for resetting the tapdance though, so we couldn't do the negative tapping term.

2022-06-16 00:13 UTC, kurtis-lew commented
Good call. Thanks for the clarification 👍

2025-06-17 17:34 UTC, caksoylar commented on app/src/behaviors/behavior_tap_dance.c
> +            behavior_keymap_binding_pressed(&tap_dance->config->behaviors[tap_dance->counter - 1],
FYI you should use `zmk_behavior_invoke_binding` instead, see https://github.com/zmkfirmware/zmk/commit/9e36ebd52587c0364562057466a458fdcfcdc685#diff-7eeba6e44a877bcea40b140ff0aaed1559f31fdea34ba7f71f0223b84c68e881

2025-06-17 22:00 UTC, nickconway commented on app/src/behaviors/behavior_tap_dance.c
> +            behavior_keymap_binding_pressed(&tap_dance->config->behaviors[tap_dance->counter - 1],
Fixed!

2026-04-29 14:44 UTC, closed without merging