Boot protocol support (based on #1140, with some refactoring)
zmkfirmware/zmk pull request #1793
Opened 2023-05-08 10:29 UTC by chrisandreae

This PR adding boot protocol support is based on @rbitanga's https://github.com/zmkfirmware/zmk/pull/1140, with some refactoring and other changes that we think are improvements, and is rebased and presented for review as @joelspadin requested [here](https://github.com/zmkfirmware/zmk/pull/1140#issuecomment-1317924785) (sorry about the huge delay!). The work was largely done by @thefloweringash.

The changes from #1140 are as follows:
* Minimize the api changes for Bluetooth by keeping `zmk_hid_get_keyboard_report()` and returning the .body like before.
* Keeping the logic about "full" vs "body" entirely within the usb code path.
* The endpoint now calls either `zmk_usb_hid_send_keyboard_report()` and   `zmk_usb_hid_send_consumer_report()` instead of `zmk_usb_hid_send_report(...)`.
    - These functions now internally dispatch on protocol to either       `zmk_hid_get_keyboard_report()` or a new function for boot reports      `zmk_hid_get_boot_report()`.
    - There's a change here from the PR version in the behavior of `get_report()`: when in boot protocol, don't include the report id. I believe this is correct, in that implicit boot protocol report descriptor does not use       multiple reports, so any boot protocol report should not include the report       id field.
* Use a single definition of a boot report, used for regular reports in
  non-6KRO, and for rollover in all branches.
* Handle gaps in the zmk report when producing a boot report in HKRO mode. For example, if it was 8KRO, it would be possible to have the state `0 0 0 0 0 0 0 17` (by pressing 8 keys, and letting go of the first 7). Copying the first 6 bytes would not show up the single pressed key.

2023-10-22 18:10 UTC, typorian commented
Any chance to get this looked at again? It'd be really neat to use my kyria to type in my bitlocker password.

2023-11-10 04:51 UTC, petejohanson requested changes
Just a few minor things. On a whole this looks good.

2023-11-10 04:51 UTC, petejohanson commented on app/Kconfig
> +    default 1
menuconfig mentions this Kconfig as deprecated:

```
Name: USB_HID_PROTOCOL_CODE
Prompt: HID Boot Interface protocol code (DEPRECATED)
Type: int
Value:

Help:

  This option is deprecated.
  Please use usb_hid_set_proto_code() instead.
```

so we should probably switch to using that API instead.

2023-11-10 04:51 UTC, petejohanson commented on app/include/zmk/hid.h
> +    uint8_t keys[6];
```suggestion
    uint8_t keys[HID_BOOT_KEY_LEN];
```

2023-11-10 04:51 UTC, petejohanson commented on app/include/zmk/hid.h
> +#else
Nice

2023-11-10 04:51 UTC, petejohanson commented on app/src/usb_hid.c
> +
These are defined now in `hid.h` now that #1993 is in. Please rebase and leverage those.

2023-11-13 17:56 UTC, petejohanson approved these changes
LGTM. Tested here on several BIOSes and on Linux, Android and Windows here and no impact to existing USB functionality. Thanks!

2023-11-13 18:04 UTC, merged

2023-11-14 11:49 UTC, typorian commented
@petejohanson Thank you very much for getting this moved along. I'm not sure how to diagnose this, but after entering my bitlocker pin (which works now, yay!) I have to reconnect the keyboard at the login screen, because now it doesn't immediately work there anymore. Unfortunately I only have this one thinkpad with bitlocker where I can test this.