doc: additional tip detailing missing &kp
zmkfirmware/zmk pull request #1933
Opened 2023-09-11 16:09 UTC by JeppeKlitgaard

This adds a small tip to the troubleshooting documentation. I made this embarrassing mistake today, but thought a more complicated `&lt` was to blame, which lead to a bit of head scratching.

2023-09-11 18:11 UTC, caksoylar requested changes
Good tip, one suggestion to highlight that it is specific to this error type.

2023-09-11 18:11 UTC, caksoylar commented on docs/docs/troubleshooting.md
> +A common mistake is to enter the keycodes directly without the leading `&kp` behavior. That is, having entries such as `SPACE` that should have been `&kp SPACE`.
```suggestion
A common mistake that leads to this error is to use keycodes without the leading `&kp` behavior. That is, having entries such as `SPACE` that should have been `&kp SPACE`.
```

2023-09-11 19:48 UTC, JeppeKlitgaard commented on docs/docs/troubleshooting.md
> +A common mistake is to enter the keycodes directly without the leading `&kp` behavior. That is, having entries such as `SPACE` that should have been `&kp SPACE`.
Agreed! Thanks!

2023-09-12 06:27 UTC, caksoylar commented on docs/docs/troubleshooting.md
> +A common mistake that leads to this error is to use keycodes without the leading `&kp` behavior. That is, having entries such as `SPACE` that should have been `&kp SPACE`.
```suggestion
A common mistake that leads to this error is to use [key press keycodes](behaviors/key-press.md) without the leading `&kp` binding. That is, having entries such as `SPACE` that should have been `&kp SPACE`.
```

2023-09-12 06:31 UTC, caksoylar approved these changes

2023-09-12 06:32 UTC, merged