feat(docs): Document globe key specific quirks
zmkfirmware/zmk pull request #1960
Opened 2023-10-09 14:12 UTC by ReFil

Adds the footnote for the issues documented with the new apple globe keycode discovered by some users in #1938

2023-10-09 22:18 UTC, caksoylar requested changes
Thanks! One fix suggestion for consistency with rest of the docs.

2023-10-09 22:18 UTC, caksoylar commented on docs/docs/codes/_footnotes/globe.mdx
> +Does not exactly replicate original key behaviour on macOS, works for Globe+key modifiers but not Fn+key ([#1938](https://github.com/zmkfirmware/zmk/pull/1938#issuecomment-1744579039)).
```suggestion
Does not exactly replicate original key behavior on macOS, works for Globe+key modifiers but not Fn+key ([#1938](https://github.com/zmkfirmware/zmk/pull/1938#issuecomment-1744579039)).
```

2023-10-10 20:49 UTC, ReFil commented
Sorry about that, should be sorted now :)

2023-10-10 21:04 UTC, caksoylar approved these changes

2023-10-10 21:04 UTC, merged