feat(hid): Add KConfig option for higher NKRO usages
zmkfirmware/zmk pull request #2024
Opened 2023-11-15 21:25 UTC by ReFil

By default, the maximum NKRO usage is set to maximize compatibility, but some keys don't work. This adds the ability to use those extended keys, at the cost of compatibility (android doesn't like the higher usage range, it seems). The chosen max was largely arbitrary, although it needs to be a multiple of 8 - 1 (otherwise windows will refuse to enumerate it properly, reporting "driver error"), For this reason I made it a configurable bool rather than a variable value. There's also no reason to have it variable across a wide range, a low and a high value seem like a good compromise

This fix addresses #1460 and is linked to #1236

2023-11-15 21:43 UTC, caksoylar reviewed
The docs LGTM other than one improvement suggestion.

2023-11-15 21:43 UTC, caksoylar commented on docs/docs/config/system.md
> +By default the NKRO max usage is set so as to maximise compatibility, however certain less frequently used keys (F13-F24 and INTL1-8) will not work. The solution is to set 'CONFIG_ZMK_HID_KEYBOARD_NK
```suggestion
By default the NKRO max usage is set so as to maximize compatibility, however certain less frequently used keys (F13-F24 and INTL1-8) will not work with it. One solution is to set `CONFIG_ZMK_HID_KEYBOARD_NKRO_EXTENDED_REPORT=y`, however this is known to break compatibility with Android and thus not enabled by default.
```

2023-11-28 00:15 UTC, petejohanson requested changes
One comment on the Kconfig details.

2023-11-28 00:15 UTC, petejohanson commented on app/Kconfig
> +endif
This should probably depend on the NKRO option:

```suggestion
config ZMK_HID_KEYBOARD_NKRO_EXTENDED_REPORT
    bool "Enable extended NKRO reporting"
    default n
    depends on ZMK_HID_REPORT_TYPE_NKRO

```

2023-11-30 01:43 UTC, petejohanson requested changes
Couple minor things I missed the first time.

2023-11-30 01:43 UTC, petejohanson commented on app/Kconfig
> +    default n
Sorry, I don't always remember to do this properly, but the default for booleans is already no, so this is redundant, and can even cause issues sometimes.


```suggestion
```

2023-11-30 01:43 UTC, petejohanson commented on app/Kconfig
> +    depends on ZMK_HID_REPORT_TYPE_NKRO
It would be nice to add a `help` section here that also warns of the Android compatibility risk

2023-12-04 23:22 UTC, petejohanson approved these changes

2023-12-04 23:24 UTC, merged