Added documentation for multiple battery monitoring
zmkfirmware/zmk pull request #2167
Opened 2024-02-15 19:30 UTC by dennisorlando

addressed by #2166

2024-02-16 10:01 UTC, dennisorlando commented on docs/docs/config/battery.md
> +If you want to report the battery levels of both sides of a split keyboard, you should have both `CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY` and `CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_QUE
*facepalm* my bad, I copy-pasted the wrong configuration item; it is supposed to be `CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING` and not `...QUEUE_SIZE`.

2024-02-16 10:15 UTC, dennisorlando commented on docs/docs/features/battery.md
> +For split keyboards, only the battery level of the central (usually left) side is reported over bluetooth. You can configure ZMK to report the battery levels of both sides, but there's no guarantee t
Meh, it's not like virtually no host will display both values: from the original pull request #2045, it appears that macOS natively shows both battery values, which if true would make up for a big percentage of users. 
Should we still write "virtually all hosts will not display this information"?
By the way, which "ZMK default widgets" are you referring to?

2024-02-16 10:29 UTC, dennisorlando commented on docs/docs/config/battery.md
That's actually the case, those options are disabled by default.
I wanted to modify this page in order to mention that it is actually possible to monitor both battery levels; if not, then people (just like I did) will suppose that it's just not possible, which will make them not even try to find a solution. If you google the issue, you don't find anything -> [only reddit post that comes up from googling "zmk split battery monitoring"](https://www.reddit.com/r/ErgoMechKeyboards/comments/xvl77l/getting_battery_levels_for_both_sides_of_split/)

Hmmm I agree that the program shoudln't be linked; I think a blog post on ZMK would be cool

2024-02-16 11:01 UTC, dennisorlando commented on docs/docs/features/battery.md
> +For split keyboards, only the battery level of the central (usually left) side is reported over bluetooth. You can configure ZMK to report the battery levels of both sides, but there's no guarantee t
(I've modified the section as suggested but instead of linkind to ../config/system, I linked to ../config/battery

2024-02-16 12:24 UTC, dennisorlando commented on docs/docs/features/battery.md
> +For split keyboards, only the battery level of the central (usually left) side is reported over bluetooth. You can configure ZMK to report the battery levels of both sides, but there's no guarantee t
Ohhh
Nope, sorry 😅
Someone else would have to check that.
I found [this post](https://www.reddit.com/r/CustomKeyboards/comments/koc9hw/finally_fully_wireless_soflezmknicenano/) which shows two different battery levels on the display, not sure if it's relevant

2024-02-16 19:29 UTC, caksoylar commented on docs/docs/features/battery.md
> +For split keyboards, only the battery level of the central (usually left) side is reported over bluetooth. You can configure ZMK to report the battery levels of both sides, but there's no guarantee t
It requires custom code to do that, the default status screens don't support that indeed.

2024-02-16 19:33 UTC, caksoylar commented on docs/docs/config/battery.md
The absence of ways to actually display the multiple battery level information was my main hang-up on expanding this documentation. I also am not a big fan of directly linking to 3rd party projects in the docs, but I'd like to hear others' opinions on it.

That being said, the current status of the PR seems like a strict improvement over the status quo.

2024-02-16 19:40 UTC, caksoylar requested changes

2024-02-16 19:40 UTC, caksoylar commented on docs/docs/config/battery.md
> +You can [configure ZMK to allow support for peripheral battery monitoring over BLE](../config/system#split-keyboards) (e.g. when having a split keyboard with two independent and wirelessly connected
```suggestion
You can [configure ZMK to allow support for peripheral battery monitoring over BLE](system.md#split-keyboards) (e.g. when having a split keyboard with two independent and wirelessly connected sides).
```

Technical nit: We prefer path-based linking in docs.

2024-02-16 19:40 UTC, caksoylar commented on docs/docs/features/battery.md
> +For split keyboards, only the battery level of the central (usually left) side is reported over bluetooth by default. ZMK can be [configured to report the battery levels for peripherals](../config/ba
```suggestion
For split keyboards, only the battery level of the central (usually left) side is reported over bluetooth by default. ZMK can be [configured to report the battery levels for peripherals](../config/battery.md#peripheral-battery-monitoring), but virtually no host system will display this information without additional configuration or the use of third party utilities.
```

2024-02-16 21:34 UTC, dennisorlando commented on docs/docs/features/battery.md
> +For split keyboards, only the battery level of the central (usually left) side is reported over bluetooth. You can configure ZMK to report the battery levels of both sides, but there's no guarantee t
> > Meh, it's not like virtually no host will display both values: from the original pull request #2045, it appears that macOS natively shows both battery values, which if true would make up for a big percentage of users. Should we still write "virtually all hosts will not display this information"?
> 
> I missed this; in the pull request before Pete took over (#1243) Katona had to write an application for macOS to display this information, and I assumed that was still the status quo. "many hosts", then.
> 
> > By the way, which "ZMK default widgets" are you referring to?
> 
> ZMK's built-in display widgets. The ones used by default if you have a display, such as an OLED, on your keyboard. (...It sounds like you don't have one.)

done

2024-02-16 21:37 UTC, dennisorlando commented on docs/docs/config/battery.md
I think that solutions will start to pop up once the docs mention the issue; there are some scripts out there which display both battery levels, they are just not that easy to find.
I myself will probably start working on a GNOME extension in the near future

2024-02-17 23:48 UTC, caksoylar approved these changes
LGTM but I'll wait for @lesshonor 's input.

2024-02-18 05:51 UTC, merged

2024-07-03 01:42 UTC, nVitius commented on docs/docs/config/battery.md
On the topic of displaying battery levels, I recently opened a PR that addresses this in the same way that MoErgo did for their Glove80:
https://github.com/zmkfirmware/zmk/pull/2353

It adds support for displaying battery level via RGB underglow on the keyboard.