add underglow for reviung5
zmkfirmware/zmk pull request #2191
Opened 2024-03-07 20:42 UTC by FearlessSpiff

Adds underglow for the reviung5. Was just coping stuff from other reviungs. And created battery optimized keymap by toggling ext power off instead of just switching RGB on and off.

Looks nice :-D
![R0000581-01](https://github.com/zmkfirmware/zmk/assets/1927259/b6479fbb-112c-416f-9025-7582b513a630)

2024-04-11 06:38 UTC, FearlessSpiff commented on app/boards/shields/reviung5/reviung5.keymap
> +                     &ext_power EP_TOG   &rgb_ug RGB_EFR   &rgb_ug RGB_EFF   &rgb_ug RGB_COLOR_HSB(307,89,98)   &trans
Cool. Didn't know that. I guess I'll just create one commit for all your suggested changes when I get time for it.

2024-04-11 06:43 UTC, FearlessSpiff commented on app/boards/shields/reviung5/reviung5.keymap
> +              sensor-bindings = <&inc_dec_kp C_VOL_DN C_VOL_UP>;
If doing it like that, then the direction is wrong.  Clockwise -> Volume down. This might be a problem with the Reviung5 design then?

2024-04-11 06:43 UTC, FearlessSpiff commented on app/boards/shields/reviung5/reviung5.keymap
> +              bindings = <&rgb_ug RGB_BRD>, <&rgb_ug RGB_BRI>;
See previous comment.

2024-04-11 07:01 UTC, FearlessSpiff commented on app/boards/shields/reviung5/reviung5.keymap
> +              sensor-bindings = <&inc_dec_kp C_VOL_DN C_VOL_UP>;
Or there might be some bug somewhere else in the reviung5 zmk code?

2024-04-11 07:06 UTC, caksoylar commented on app/boards/shields/reviung5/reviung5.keymap
> +              sensor-bindings = <&inc_dec_kp C_VOL_DN C_VOL_UP>;
That would be the symptom if A and B encoder pins are swapped around.

2024-04-11 09:20 UTC, FearlessSpiff commented on app/boards/shields/reviung5/reviung5.keymap
> +              sensor-bindings = <&inc_dec_kp C_VOL_DN C_VOL_UP>;
I'll check it later in the weekend. Family aso...

2024-04-11 09:24 UTC, FearlessSpiff commented
> I'm going to leave actionable suggestions in good faith, but don't hold your breath on this getting merged.

Why do you think that. It is almost the same code as with the other reviungs. In fact I think I just changed the number of LEDs... And the keymap obviously.

2024-04-16 20:52 UTC, FearlessSpiff commented on app/boards/shields/reviung5/reviung5.keymap
> +              sensor-bindings = <&inc_dec_kp C_VOL_DN C_VOL_UP>;
According to the schematics [1] the overlay [2] seams correct. No idea why it's reversed. Might measure it later. But for correctness I am going to change it back in the keymap and just turn it in my own keymap. 

[1] https://github.com/gtips/reviung/blob/master/reviung5/pcb/ver1.0/circuit_diagram.pdf
[2] https://github.com/zmkfirmware/zmk/blob/main/app/boards/shields/reviung5/reviung5.overlay

2024-04-17 09:44 UTC, FearlessSpiff commented on app/boards/shields/reviung5/reviung5.keymap
> +              sensor-bindings = <&inc_dec_kp C_VOL_DN C_VOL_UP>;
Done: 1dcef5f03496fcb458836e0d102924e4de5e5876

2024-04-17 09:45 UTC, FearlessSpiff commented on app/boards/shields/reviung5/reviung5.keymap
> +              bindings = <&rgb_ug RGB_BRD>, <&rgb_ug RGB_BRI>;
Done: 1dcef5f03496fcb458836e0d102924e4de5e5876

2024-04-17 09:45 UTC, FearlessSpiff commented on app/boards/shields/reviung5/reviung5.keymap
> +                     &ext_power EP_TOG   &rgb_ug RGB_EFR   &rgb_ug RGB_EFF   &rgb_ug RGB_COLOR_HSB(307,89,98)   &trans
Done: 548e8d17186c7c8d37c80320254335c2307ed8a1

2024-04-17 09:46 UTC, FearlessSpiff commented on app/boards/shields/reviung5/reviung5.keymap
> +#include <dt-bindings/zmk/ext_power.h>
Done: 548e8d17186c7c8d37c80320254335c2307ed8a1

2025-03-29 11:16 UTC, nmunnich requested changes
Thanks for the PR! I'd like to merge this. Could you please tidy up your commit history following our guidelines? https://zmk.dev/docs/development/contributing/pull-requests

2025-05-04 11:14 UTC, FearlessSpiff commented
Sorry, live and family... Is this a better commit message? Not sure tbh...

2025-05-04 11:27 UTC, FearlessSpiff commented
Oh, build problems... Have to check that later.

2025-05-05 08:58 UTC, nmunnich commented
> Oh, build problems... Have to check that later.

This might be me being silly, but the tests aren't showing any build issues. Where are you getting the build issues?

2025-05-05 18:20 UTC, FearlessSpiff commented
> > Oh, build problems... Have to check that later.
> 
> This might be me being silly, but the tests aren't showing any build issues. Where are you getting the build issues?

Yes, I thought I got a mail from github, that it failed. But I now even successfully compiled and flashed it. Everything works great.

2025-05-05 18:46 UTC, nmunnich approved these changes

2025-05-05 18:46 UTC, merged