feat(docs): Update section for devicetree_generated error
zmkfirmware/zmk pull request #2248
Opened 2024-04-04 00:07 UTC by filterpaper

* Update error string to reflect current version
* Merge them under the same devicetree errors title

2024-04-04 02:18 UTC, filterpaper commented on docs/docs/troubleshooting.md
>  /__w/zmk-config/zmk-config/build/zephyr/include/generated/devicetree_unfixed.h:3756:145: error: 'DT_N_S_keymap_S_symbol_layer_P_bindings_IDX_12_PH_P_label' undeclared here (not in a function); did yo
Thank you

2024-04-04 16:53 UTC, caksoylar requested changes
LGTM besides this nit, thanks for following up from #2212!

2024-04-04 16:53 UTC, caksoylar commented on docs/docs/troubleshooting.md
> +#### devicetree errors
```suggestion
#### Devicetree errors
```
Nit, but now we don't mean `devicetree error` as an entity so this makes more sense to me.

2024-04-05 01:31 UTC, caksoylar approved these changes

2024-04-05 01:31 UTC, merged