New behavior for ext power control
zmkfirmware/zmk pull request #258
Opened 2020-10-10 02:40 UTC by megamind4089

Added behaviors to control the external power output.

Tested with nRFMicro 1.3 and Lily58

_Note:_ Still need to test with nice!nano

2020-10-10 16:33 UTC, innovaker commented
Thanks @megamind4089!

A couple of Qs on this for @petejohanson:
- Should this be achieved with different behavior tags rather than using a flag?
- Can the shield enhancements be a separate commit? (same PR)

2020-10-10 17:02 UTC, petejohanson commented
> Thanks @megamind4089!
> 
> A couple of Qs on this for @petejohanson:
> - Should this be achieved with different behavior tags rather than using a flag?
> - Can the shield enhancements be a separate commit? (same PR)

Using the flag like is there is fine.

I'm not convinced we need the two parameters though. I would think for auto we would just pass `EP_AUTO` and that's that. Leaving as single parameter allows for using this with the hold-tap meta behavior.

2020-10-10 18:04 UTC, innovaker commented
Thanks!

I was wondering how we should differentiate between behavior tags and switches (flags) across all behaviors?  What convention should we encourage?  Together, they effectively mean "*do this, in this way*".  It could also be achieved with two tags belonging to the same behavior, effectively `&on` and `&off` - which also optimizes the keymap.

2020-10-11 16:37 UTC, megamind4089 commented
@innovaker I just used Lily58 to test this behavior and updated with this. I am happy to raise a new PR for shields also.

@petejohanson I have removed the second parameter to the behavior.
Also added toggle behavior as discussed

2020-10-12 15:00 UTC, petejohanson requested changes
This is a great start on this. A few tweaks needed.

I think in general, using the "command parameter" like this is good, it avoids "driver instance proliferation", and leverages the argument infrastructure reasonably.

2020-10-12 15:53 UTC, megamind4089 commented on app/src/behaviors/behavior_ext_power.c
> +    const struct ext_power_api *ext_power_api = ext_power->driver_api;
What a shame I did. :cry:

2020-10-12 15:57 UTC, petejohanson reviewed
Couple minor tweaks.

2020-10-12 15:57 UTC, petejohanson commented on app/dts/bindings/behaviors/zmk,behavior-ext-power.yaml
> +include: two_param.yaml
Should be:

```suggestion
include: one_param.yaml
```

2020-10-12 15:57 UTC, petejohanson commented on app/dts/behaviors/ext_power.dtsi
> +			#binding-cells = <2>;
Doesn't need two:

```suggestion
			#binding-cells = <1>;
```

2020-10-12 15:57 UTC, petejohanson commented on app/src/behaviors/behavior_ext_power.c
> +    const struct ext_power_api *ext_power_api = ext_power->driver_api;
All good!

2020-10-13 04:01 UTC, petejohanson approved these changes
@megamind4089 This is great! Can you please work on documenting the new behavior in a follow up?

Thanks again.

2020-10-13 04:01 UTC, merged