Waveshare RP2040-Zero board addition
zmkfirmware/zmk pull request #2596
Opened 2024-10-29 20:33 UTC by miketronic

## Board/Shield Check-list

- [x] This board/shield is tested working on real hardware
- [x] Definitions follow the general style of other shields/boards upstream ([Reference](https://zmk.dev/docs/development/new-shield))
- [x] `.zmk.yml` metadata file added
- [x] Proper Copyright + License headers added to applicable files (Generally, we stick to "The ZMK Contributors" for copyrights to help avoid churn when files get edited)
- [x] General consistent formatting of DeviceTree files
- [ ] N/A Keymaps do not use deprecated key defines (Check using the [upgrader tool](https://zmk.dev/docs/codes/keymap-upgrader))
- [ ] N/A `&pro_micro` used in favor of `&pro_micro_d/a` if applicable
- [ ] N/A If split, no name added for the right/peripheral half
- [x] Kconfig.defconfig file correctly wraps _all_ configuration in conditional on the shield symbol
- [ ] N/A `.conf` file has optional extra features commented out
- [x] Keyboard/PCB is part of a shipped group buy or is generally available in stock to purchase (OSH/personal projects without general availability should create a zmk-config repo instead) -- board is available from many sources.

This PR takes off from where glebsexy left off.  I attempted to make all changes that Pete mentioned in the comments of that PR (1871).

2024-10-29 20:36 UTC, Nick-Munnich commented
Are the outer pins of the zero footprint-compatible with the xiaos? Could you define an interconnect and GPIO nexuses for the zero?

I would also say that this is a board worth attempting to upstream to Zephyr, since waveshare already has some boards defined there.

2024-10-29 20:41 UTC, miketronic commented
> Are the outer pins of the zero footprint-compatible with the xiaos? Could you define an interconnect and GPIO nexuses for the zero?
> 
> I would also say that this is a board worth attempting to upstream to Zephyr, since waveshare already has some boards defined there.

The Xiao is even smaller, shorter by two pins on both sides and none of the pins opposite the USB port that the Zero has.

2024-10-29 20:43 UTC, Nick-Munnich commented
> The Xiao is even smaller, shorter by two pins on both sides and none of the pins opposite the USB port that the Zero has.

My question is more, if you have a keyboard designed for the Xiao RP2040, could you use the Zero with it or would the width/spacing not match up

2024-10-31 14:02 UTC, Nick-Munnich commented
As a consequence of them being compatible I think a xiao_d gpio nexus node should be added so that the zero can be used in place of the xiao on xiao shields.

2024-11-01 14:31 UTC, miketronic commented
Deleted the old branch and renamed the new one.

2024-11-01 15:03 UTC, miketronic commented
> As a consequence of them being compatible I think a xiao_d gpio nexus node should be added so that the zero can be used in place of the xiao on xiao shields.

Looking deeper, unfortunately they are not pin compatible unless you very specifically designed the shield with a cutout in the middle for the internals and USB connector, essentially having a "U" of the connecting pins.  5v/GND/3v3 are on opposite sides of the board for both of the MCUs.

2024-12-20 19:37 UTC, petejohanson requested changes

2024-12-20 19:37 UTC, petejohanson commented on app/boards/arm/waveshare_rp2040_zero/waveshare_rp2040_zero.dts
> +        compatible = "raspberrypi,pico-header";
This is a compatible that should only be used if this matches the physical layout of a Pi Pico board, which the Zero does not. You'll need a new compatible bindings file for this.

2024-12-20 19:37 UTC, petejohanson commented on app/boards/arm/waveshare_rp2040_zero/waveshare_rp2040_zero.dts
> +// zero_spi: &spi0 {};
Remove these instead of leaving commented out.

2024-12-20 19:37 UTC, petejohanson commented on app/boards/arm/waveshare_rp2040_zero/waveshare_rp2040_zero_defconfig
> +CONFIG_UART_CONSOLE=y
These defaults are what Zephyr recommends for their "stock board setup" but doesn't match ZMK's standards. Remove these please:

```suggestion
```

2024-12-20 19:37 UTC, petejohanson commented on app/boards/arm/waveshare_rp2040_zero/waveshare_rp2040_zero_defconfig
> +CONFIG_BUILD_OUTPUT_UF2=y
Should add lines to enable settings, flash, flash NVS, etc. by default, so we can store various settings, e.g. RGB state or studio keymaps.

2025-08-04 22:08 UTC, nmunnich commented
See #2806

2025-08-04 22:08 UTC, closed without merging