feat(underglow): RGB toggle controls ext_power
zmkfirmware/zmk pull request #346
Opened 2020-11-08 18:08 UTC by Nicell

This adds the ability for RGB underglow toggling to control ext_power to save immensely on battery when RGB is off. It also can be turned off if people want to have more fine tuned control if they have more than RGB on their board for example.

This PR also fixes the error being thrown on release of any underglow behavior and the quick blip of red LED on start when using settings.

2020-11-08 19:31 UTC, tominabox1 commented
Tested on my QAZ, zero voltage when using the RGB_TOG behavior. Nice work. 

Also testing the power on by default config and that seems to be working as expected also.

2020-11-23 01:24 UTC, petejohanson requested changes
Just one minor comment. Thanks!

2020-11-23 01:24 UTC, petejohanson commented on app/src/rgb_underglow.c
> +    struct device *ext_power = device_get_binding("EXT_POWER");
I would just initialize a static variable in the init once, instead of fetching each time.

2020-11-23 02:04 UTC, petejohanson requested changes
One more item. Thanks!

2020-11-23 02:04 UTC, petejohanson commented on app/src/rgb_underglow.c
> +    ext_power = device_get_binding("EXT_POWER");
You should change this to be wrapped in an `#if`, same with the actual declaration of the static variable.

2020-11-23 02:23 UTC, petejohanson approved these changes
Perfect! Thanks.

2020-11-23 02:23 UTC, merged