Create west command to run tests
zmkfirmware/zmk pull request #385
Opened 2020-11-14 18:51 UTC by okke-formsma

This PR adds  West command 'test' that runs our testsuite.

For now it adds little value, but this opens the way to run the testsuite from python instead of a bash script. This may enable us to run the tests on Windows and add nice things like pretty printing.

2020-11-16 22:31 UTC, petejohanson requested changes
Can we update our GitHub workflow to invoke the tests this way, to be sure this continues working and doesn't regress?

2020-11-18 20:48 UTC, okke-formsma commented
The `west test` command can now be run in any directory (not necessarily `app`) and exits with the correct exit code.

2020-11-21 16:02 UTC, petejohanson requested changes
Looks generally good. One missing header, and this needs a rebase, then we can merge.

2020-11-21 16:02 UTC, petejohanson commented on app/scripts/west-commands.yml
> +west-commands:
Please add a copyright/license header.

2020-11-21 19:40 UTC, okke-formsma commented
@petejohanson fixed, ready for merge

2020-11-21 19:44 UTC, innovaker commented on app/scripts/west-commands.yml
> +        help: run zmk testsuite
```suggestion
        help: run ZMK testsuite
```

2020-11-21 19:46 UTC, petejohanson approved these changes
Perfect! Thanks.

2020-11-21 19:47 UTC, merged