(feature) Add &to keycode/behavior
zmkfirmware/zmk pull request #489
Opened 2020-12-07 19:35 UTC by mcrosson

Add `&to` behavior/key code to allow enabling a layer while also disabling all other layers. Similar to toggle but includes the disable part that's not included in the toggle behavior.

Code was modeled after the `&tog` behavior.

2020-12-08 18:56 UTC, okke-formsma reviewed
looks good! I think it makes sense to get rid of the loop in zmk_keymap_layer_to, otherwise perfect.

2020-12-08 18:56 UTC, okke-formsma commented on app/src/keymap.c
> +        zmk_keymap_layer_deactivate(i);
`zmk_keymap_layer_state = 0` is an easier way of writing this loop.

2020-12-11 19:25 UTC, mcrosson commented
Per Discord conversation( https://discord.com/channels/719497620560543766/719565084208398406/787032810523066409) updated PR with appropriate is layer active logic as well as tweaked the way layers are deactivated in the &to key code handling

2020-12-11 19:39 UTC, okke-formsma commented
to make sure the implementation is correct and doesn't break in the future, please add some tests. Scenarios to consider

* &to from layer 0 to layer 1, verify no layer release event is emitted for default layer, verify a layer active event is sent for the new layer
* &to from layer 1 to the default layer, verify a layer release for layer 1
* &to from layer 1 to layer 1, verify either no layer events for layer 1 are emitted (it was already active so the &to should not fire any events imo)

2020-12-15 03:24 UTC, mcrosson commented
@okke-formsma I added a set of test cases similar to what you suggested. I'm not sure I got them 100% but I think they are close if nothing else, can you review and let me know?

2020-12-15 03:33 UTC, mcrosson commented
Looks like the new test failed but I'm unsure how/why...

2020-12-16 19:44 UTC, okke-formsma requested changes
overall good! I think we need to find a way to limit the number of triggered events somewhat.

2020-12-16 19:44 UTC, okke-formsma commented on app/src/keymap.c
> +int zmk_keymap_layer_to(uint8_t layer) {
this method causes 32 layer_state_changed events (31 for disabling all layers except the default layer + 1 for enabling the to-layer).

Layer-changed-events should only be triggered if the layer state actually changes.

Not sure if the layer that is being moved to should be disabled & enabled again (or just kept enabled if it was already enabled). I don't have a strong opinion on this.

2020-12-16 19:44 UTC, okke-formsma commented on app/tests/to-layer/normal/events.patterns
> +s/.*to_keymap_binding/to/p
Please add some pattern to record all layer-state-changed events, so you can verify which layer state changed events are seen.

2020-12-16 19:44 UTC, okke-formsma commented on app/src/keymap.c
> +    for (int i = 0; i < 32; i++) {
as per joels suggestion, maybe add a define for mx layers

```c
#define MAX_LAYERS (sizeof(the_layer_variable) * 8)
```

2020-12-18 23:33 UTC, mcrosson commented
Number of events is greatly reduced -- reduced to only the affected layers ; also added debug info/test snapshot to match expectations

2020-12-19 21:04 UTC, okke-formsma requested changes

2020-12-19 21:04 UTC, okke-formsma commented on app/src/keymap.c
> +    if (layer != zmk_keymap_layer_default() && zmk_keymap_layer_active(layer)) {
There's a bug in here; if layers 0, 1, 2, 3 are active, and going TO layer 1, layers 2 and 3 should be disabled.

2020-12-19 21:04 UTC, okke-formsma commented on docs/docs/behaviors/layers.md
> +The "to layer" behavior enables a layer and disables _all_ other layers.
maybe add a note about excluding the default layer.

2020-12-21 21:09 UTC, okke-formsma commented
lgtm @mcrosson I think it's time to rebase and get this onto Pete's plate.

2020-12-21 21:10 UTC, okke-formsma approved these changes
lgtm. Let's rebase and get it onto Pete's plat.

2020-12-21 21:19 UTC, mcrosson commented
Rebased to latest main branch, squashed and ready for @petejohanson

2020-12-28 05:51 UTC, petejohanson requested changes
Just one nitpick, otherwise this looks good. Thanks!

2020-12-28 05:51 UTC, petejohanson commented on app/src/behaviors/behavior_to_layer.c
> +static const struct behavior_to_config behavior_to_config = {};
There's some cruft inherited from other behaviors in our code, but we don't need to carry it forward... If you don't use any config, or data, you can skip defining these types, declaring instances, and just pass `NULL` for these two fields to the device init macro.

2020-12-29 13:25 UTC, petejohanson requested changes
Missed one thing. Sorry.

2020-12-29 13:25 UTC, petejohanson commented on app/src/keymap.c
> +#define MAX_LAYERS (sizeof(_zmk_keymap_layer_state) * 8)
We have a define for this, check maybe keymap.h?

2020-12-29 16:16 UTC, petejohanson requested changes
Sorry, I keep doing the "one more thing" review approach, which sucks. This really is close, I promise.

2020-12-29 16:16 UTC, petejohanson commented on app/include/zmk/keymap.h
> +bool zmk_keymap_layer_active_with_state(uint8_t layer, zmk_keymap_layers_state_t state_to_test);
Sorry, one last thing I missed. This is only used internally in `keymap.c`, we shouldn't publish this method yet, unless it's actually needed.

2020-12-29 16:56 UTC, petejohanson approved these changes
Sweet!

2020-12-29 16:57 UTC, merged