Planck keymap
zmkfirmware/zmk pull request #505
Opened 2020-12-11 22:54 UTC by ReFil

This is a port of the QMK planck keymap. Given the one for the CRBN is identical I fixed it at the same time. I think I followed the indentation guidelines this time

2020-12-30 18:55 UTC, Nicell commented
Would be nice to get a proper default mapping for the Planck. Although, do we have anyone with the Planck that can test this? I'm not aware of anyone at least. At the very least, I assume you've tested this mapping on your CRBN @ReFil?

2020-12-30 19:29 UTC, ReFil commented
Yeah it's been thoroughly tested on the CRBN, by our customers too, I haven't got a planck to test it on but it builds fine

2020-12-30 19:35 UTC, innovaker commented
@petejohanson was the original author of the planck shield so it might be wise to add him as a reviewer once you're satisfied with everything else @Nicell.

2021-02-04 13:41 UTC, ReFil commented
Hiya, just wondering what's happening with this PR as I've got some more stuff for the CRBN waiting in the wings but i wanted to get this merged first

2021-02-04 18:54 UTC, Nicell requested changes
I have some indentation comments, but otherwise this looks fine. There's also a conflict now that the CRBN encoder stuff is in.

2021-02-04 18:54 UTC, Nicell commented on app/boards/arm/planck/planck_rev6.keymap
> +	 };
```suggestion
		};
```
Looks like just this one line was misaligned

2021-02-04 18:54 UTC, Nicell commented on app/boards/arm/planck/planck_rev6.keymap
> +	compatible = "zmk,keymap";
```suggestion
		compatible = "zmk,keymap";
```
I think this indentation should be back to how it was before

2021-02-04 18:54 UTC, Nicell commented on app/boards/shields/crbn/crbn.keymap
> +	compatible = "zmk,keymap";
```suggestion
		compatible = "zmk,keymap";
```

2021-02-04 18:54 UTC, Nicell commented on app/boards/shields/crbn/crbn.keymap
> +	 };
```suggestion
		};
```

2021-02-04 21:38 UTC, ReFil commented
Ok I'll fix the encoder stuff tonight then :)

2021-02-04 23:02 UTC, ReFil commented
Encoder stuff added to crbn keymap

2021-02-05 00:08 UTC, ReFil commented
Fixed the conflict, changed the mapping of the encoder slightly, it does pgup and pgdn on raise layer and vol on default to try and please all our customers as we've been giving them builds with the encoder mapped to vol to date (we were waiting for this to get merged before submitting a pr for our encoder support but someone beat us to it haha)

2021-02-12 11:17 UTC, ReFil commented
Hi guys is there anything more i need to do to get this merged? It's rebased to latest and has no conflicts so should be good to go

2021-02-12 17:10 UTC, innovaker commented
> Hi guys is there anything more i need to do to get this merged? It's rebased to latest and has no conflicts so should be good to go

Sorry for the delay and thank you for your patience.  We're in the midst of upgrading shield submissions so that we can accept shield PRs in parallel rather than series (which created the backlog you see today).  See #653 which is the leading edge of that overhaul.  I'm guessing this PR will be accepted after that's completed otherwise we're shooting a moving target.

In the meantime, this PR seems to replace all the line endings in  `docs/static/setup.ps1` - which it shouldn't.  You might want to check that.

2021-02-12 19:23 UTC, ReFil commented
oh god dammit not again. I had that issue last time i tried to submit a pr. I didn't even change anything in setup.ps1 haha

2022-09-22 19:12 UTC, petejohanson approved these changes
OH YEAH!

2022-09-22 19:14 UTC, merged