docs(sticky keys): document sticky keys and sticky layers
zmkfirmware/zmk pull request #511
Opened 2020-12-13 13:44 UTC by okke-formsma

fixes #439, missing sticky keys and sticky layers documentation

2021-01-01 22:02 UTC, Nicell requested changes

2021-01-01 22:02 UTC, Nicell commented on docs/docs/behaviors/sticky-layer.md
> +A sticky layer stays pressed until another key is pressed. By using a sticky layer, you don't have to hold te layer key to access a layer. Instead, tap the sticky layer key to active the layer until
```suggestion
A sticky layer stays pressed until another key is pressed. By using a sticky layer, you don't have to hold the layer key to access a layer. Instead, tap the sticky layer key to activate the layer until the next keypress.
```

2021-01-01 22:02 UTC, Nicell commented on docs/docs/behaviors/sticky-layer.md
> +Sticky layers behave slightly different from stick keys. They are configured to `quick-release`. This means that the layer is released immediately when another key is pressed. "Normal" sticky keys ar
```suggestion
Sticky layers behave slightly different from sticky keys. They are configured to `quick-release`. This means that the layer is released immediately when another key is pressed. "Normal" sticky keys are not `quick-release`; they are released when the next key is released. This makes it possible to combine sticky layers and sticky keys as such: tap `&sl 1`, tap `&sk LSHFT` on layer 1, tap `&kp A` on base layer to output shift+A.
```

2021-01-09 19:36 UTC, Nicell approved these changes
LGTM!

2021-01-25 04:29 UTC, petejohanson approved these changes

2021-01-25 04:30 UTC, merged