(fix) tg4x Misc (See desc)
zmkfirmware/zmk pull request #567
Opened 2021-01-02 04:38 UTC by mcrosson

Various fixes / cleanup

* compile warnings
* keymaps updated to match upstream
* add readme
* add underglow

2021-01-02 12:46 UTC, innovaker commented
This is arguably a good example of the difference between a new feature PR and an improvements or fixes PR.

For a new feature PR, bundling it all together is (usually) fine because it's all part of the same package.  It's atomic in itself.

For further fixes and improvements however, it's better to use atomic commits.  So each of those bullet points would probably be a different commit.  Same PR, sure, but different commits.  It makes reviewing and tracing easier and it also gives you more "room" for detailing context or reasoning within commit messages.  It's simple to do, you just commit as you go - but it's a habit that doesn't seem to be intuitive to most developers.  Doing so actually helps develop general best practices because you learn to avoid making lots of changes at once, which is critical for developing complex systems or tracing bugs.

Perhaps look at it from this perspective (one of many potential scenarios) ... say your PR accidentally breaks some random person's keyboard.  So this poor soul starts digging through the code and finds the offending line in `tg4x.keymap`.  They look at the commit for that line to find out why it was changed.   They read: `(fix) TG4X - Keymaps ; underglow ; build warnings` and are left with these questions ...
- Why was this "fixed"?
- Why are all of these changes seemingly connected/related?  Do I need to worry about them also?
- #help!?

If the commits are atomic, the poor soul has at least got a fighting chance of figuring it out themselves.  The same applies to reviewers and maintainers.

2021-01-03 20:50 UTC, Nicell requested changes
Some naming thoughts and comments. Otherwise the changes seem pretty reasonable.

2021-01-03 20:50 UTC, Nicell commented on app/boards/shields/tg4x/Kconfig.defconfig
> +    default "tg4x"
```suggestion
    default "TG4x"
```
The silkscreen on the board shows this style of capitalization.

2021-01-03 20:50 UTC, Nicell commented on app/boards/shields/tg4x/README.md
> +# TG4X
```suggestion
# TG4x
```

2021-01-03 20:50 UTC, Nicell commented on app/boards/shields/tg4x/README.md
> +Standard setup for the [TG4X](https://github.com/MythosMann/tg4x/) 40% keyboard.
```suggestion
Standard setup for the [TG4x](https://github.com/MythosMann/tg4x/) 40% keyboard.
```

2021-01-03 20:50 UTC, Nicell commented on app/boards/shields/tg4x/README.md
> +The `keymap` directory contains the keyboard layout and were created by [Keyboard Layout Editor](http://www.keyboard-layout-editor.com/). Please note: the zmk keymap is slightly adjusted from the def
```suggestion
The `keymap` directory contains the keyboard layout and were created by [Keyboard Layout Editor](http://www.keyboard-layout-editor.com/). Please note: the ZMK keymap is slightly adjusted from the default shown on the main TG4x pages and QMK.
```

2021-01-03 20:50 UTC, Nicell commented on app/boards/shields/tg4x/README.md
> +This TG4X implementation is for...
```suggestion
This TG4x implementation is for...
```

2021-01-03 20:50 UTC, Nicell commented on app/boards/shields/tg4x/tg4x.overlay
> +RC(3,0) RC(3,1) RC(3,2) RC(3,4) RC(3,5) RC(7,1) RC(7,2) RC(7,3) RC(7,4)
Could this transform possibly have whitespace to show the size of keys better?

2021-01-04 20:00 UTC, Nicell approved these changes

2021-01-05 22:25 UTC, innovaker requested changes
You have a mix of tabs and spaces in `tg4x.overlay`.

2021-01-05 22:25 UTC, innovaker commented on app/boards/shields/tg4x/boards/nice_nano.conf
> +# Enable underglow
```suggestion
# Copyright (c) 2020 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Enable underglow
```

2021-01-05 22:25 UTC, innovaker commented on app/boards/shields/tg4x/boards/nice_nano.conf
> +# Enable underglow
```suggestion
# Copyright (c) 2020 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Enable underglow
```

2021-01-05 22:44 UTC, mcrosson commented
All changes/updates/suggestions should now be part of this PR

2021-01-08 10:14 UTC, innovaker approved these changes

2021-01-08 10:14 UTC, merged