chore: move prettier to root
zmkfirmware/zmk pull request #568
Opened 2021-01-02 12:12 UTC by innovaker

Please check this in detail as there may be subtle nuances I've missed.

2021-01-02 12:14 UTC, innovaker commented
This PR doesn't (yet?) include changes to:
- setup documentation
- `.devcontainer`

I welcome PRs to this branch.

2021-01-02 12:21 UTC, innovaker commented
Rather than maintain the prettier script commands in both the root's and docs's `package.json`, I favoured moving it solely into the root.  A consequence of this is that `npm run prettier:write` must be run from root whereas `npm run lint` is run from docs.  Thoughts?  We may also wish to consider moving `lint` to the root.

2021-01-03 21:30 UTC, Nicell requested changes
I'm not a huge fan of having the two commands being split in which directory they should be run. I'm wondering if we should add a lint command to root that runs within docs, so you don't have to move around to do your checks.

2021-01-03 21:30 UTC, Nicell commented on .prettierignore
> +/zephyr
```suggestion
/zephyr
app/build

```

2021-01-05 17:38 UTC, joelspadin commented
> I'm not a huge fan of having the two commands being split in which directory they should be run. I'm wondering if we should add a lint command to root that runs within docs, so you don't have to move around to do your checks.

Maybe there's something clever we could do with [NPM workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces) to more gracefully handle one NPM package nested inside another? Then you could just have Prettier installed in both places (hopefully done automatically by running `npm install` from the root), configure the root Prettier to ignore docs, and set up the root Prettier script to run Prettier in the root followed by running it in docs.

2021-01-05 19:39 UTC, innovaker commented
> Maybe there's something clever we could do with NPM workspaces 

Worth trying for sure 👍  Good spot.

2021-01-06 11:16 UTC, innovaker commented
> Maybe there's something clever we could do with [NPM workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces) to more gracefully handle one NPM package nested inside another?

I've tried this with by adding:
```
  "workspaces": [
    "docs"
  ],
```
to `/package.json`.

Running `npm ci` in `/` installs prettier, but it also installs the docs.  I'm not sure who it was, but I believe someone expressed an interest in avoiding that behavior?  I'm personally fine with it though.

Also, inheritance seems to be limited (???) so we'd have to:
- re-add `prettier:check` and `prettier:format` to `/docs/package.json`'s scripts and keep those lines synced with root
- copy `/.prettierrc.js` into `/docs/prettierrc.js` and keep it synced with root
- re-add `/docs/.prettierignore`

We'd be abusing the purpose of workspaces slightly, but I think the pros probably outweigh the cons.

Thoughts?

2024-04-11 06:46 UTC, closed without merging