Update underglow.md
zmkfirmware/zmk pull request #709
Opened 2021-03-01 18:23 UTC by Megamannen

Updated the documentation according to my current understandring of how to pin-mapping works, also split the chapter into a nrf-section and a non-nrf-section since that information isn't applicable to both

2021-03-01 18:38 UTC, mcrosson approved these changes
This looks good

Thank you!

2021-03-01 19:01 UTC, Nicell requested changes
Thanks for adding this information. Could you also run the prettier and linting commands? You can find a guide [here](https://deploy-preview-709--zmk.netlify.app/docs/development/documentation#formatting-and-linting-your-changes).

2021-03-01 21:44 UTC, Megamannen commented on docs/docs/features/underglow.md
>  Ignoring these restrictions may result in poor wireless performance. You can find the list of low frequency I/O pins [here](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fps_nrf52840%2Fpin.html
Done!

2021-03-03 06:02 UTC, Nicell approved these changes
Thanks!

2021-03-03 06:03 UTC, merged