Toggle key feature
zmkfirmware/zmk pull request #731
Opened 2021-03-16 20:42 UTC by okke-formsma

Requested by @mcrosson for use with artsey.

Most of the heavy lifting is done is hid.c, because that's where the current state of the keyboard can be found.

Keeping track of the hid state in the toggle would is tricky because that would mean reimplementing most of hid.c. Also it's not possible to cleanly keep track of when hid_clear methods are called, so just requesting this information from hid seemed the cleanest solution.

2021-03-18 06:27 UTC, mcrosson approved these changes
This is working 100% with ARTSEY + Shift Lock

👍 and many thanks

2021-03-23 18:50 UTC, mcrosson commented
bump @petejohanson ?

2021-06-09 22:42 UTC, mcrosson commented
@petejohanson can i bug you to look at this one, it should be small and works really well ; i've been using it since it dropped as a PR without any issues

2021-08-17 19:25 UTC, mcrosson commented
bump @petejohanson

2022-01-20 05:12 UTC, petejohanson requested changes
A few comments/tweaks needed.

Thanks!

2022-01-20 05:12 UTC, petejohanson commented on app/include/zmk/hid.h
> +bool zmk_hid_keyboard_is_pressed();
Messed up declaration?

```suggestion
bool zmk_hid_keyboard_is_pressed(zmk_key_t key);
```

2022-01-20 05:12 UTC, petejohanson commented on app/src/behaviors/behavior_key_toggle.c
> +        zmk_hid_is_pressed(HID_USAGE_PAGE(binding->param1), HID_USAGE_ID(binding->param1));
Not sure I like this API requiring pre-decoded, feels messy w/ both styles of API.

Any particular reason you took this approach?

2022-01-20 05:12 UTC, petejohanson commented on app/src/behaviors/behavior_key_toggle.c
> +static int behavior_key_toggle_init(const struct device *dev) { return 0; };
I believe you can just pass `NULL` for the init callback in the macro to define the device, instead of this empty function.

2022-01-20 05:12 UTC, petejohanson commented on app/src/hid.c
> +    for (int idx = 0; idx < ZMK_HID_KEYBOARD_NKRO_SIZE; idx++) {
This needs rebasing on the new HID code to handle NKRO or 6KRO configs, etc.

2022-04-05 20:39 UTC, cgoates commented
After discussion with @mcrosson and @okke-formsma I'm going to take on the task of rebasing this on latest main and fixing it up according to the comments here.  I'll link the other PR here once I've got one.

2022-05-21 19:14 UTC, dxmh commented
Superseded by https://github.com/zmkfirmware/zmk/pull/1278.

2022-05-21 19:14 UTC, closed without merging