Update docs to use “SQT” instead of “QUOTE”
zmkfirmware/zmk pull request #839
Opened 2021-06-14 19:43 UTC by fsargent

Default keymap used an invalid character, this sets it valid.

2021-06-14 19:53 UTC, petejohanson approved these changes
Thanks!

2021-06-14 19:54 UTC, petejohanson requested changes

2021-06-14 19:54 UTC, petejohanson commented on docs/docs/keymap-example.md
> +    &kp TAB    &kp A    &kp S    &kp D     &kp F     &kp G                                                 &kp H     &kp J     &kp K     &kp L     &kp SEMI &kp RQT
Actually, typo here:

```suggestion
    &kp TAB    &kp A    &kp S    &kp D     &kp F     &kp G                                                 &kp H     &kp J     &kp K     &kp L     &kp SEMI &kp SQT
```

2021-06-14 19:54 UTC, innovaker commented on docs/docs/keymap-example.md
> +    &kp TAB    &kp A    &kp S    &kp D     &kp F     &kp G                                                 &kp H     &kp J     &kp K     &kp L     &kp SEMI &kp RQT
```suggestion
    &kp TAB    &kp A    &kp S    &kp D     &kp F     &kp G                                                 &kp H     &kp J     &kp K     &kp L     &kp SEMI &kp SQT
```
???

2021-06-14 19:59 UTC, petejohanson commented
@innovaker https://tenor.com/XE21.gif

2021-07-27 21:19 UTC, Nicell approved these changes

2021-07-27 22:32 UTC, petejohanson approved these changes

2021-07-27 23:18 UTC, merged