Refactor Pro Micro pin mapping
zmkfirmware/zmk pull request #876
Opened 2021-07-24 19:21 UTC by Nicell

This PR refactors the Pro Micro pin mapping:

- Adds in the missing 18-21
- Renames `pro_micro_d` to `pro_micro` (`pro_micro_d` alias included for compatibility)
- Removes all uses of `pro_micro_a` in favor of `pro_micro_d` 
- Updates documentation image + description of Pro Micro pins

2021-08-03 01:54 UTC, petejohanson requested changes
Minor nitpick. Appreciate the backwards compatible approach, and getting all existing shields updated to help set proper examples moving forward.

2021-08-03 01:54 UTC, petejohanson commented on docs/docs/development/boards-shields-keymaps.md
> +  - A [chosen](https://docs.zephyrproject.org/2.5.0/guides/dts/intro.html#aliases-and-chosen-nodes) node named `zmk,kscan` which references the configured KSCAN driver (usually a GPIO matrix). For th
```suggestion
  - A [chosen](https://docs.zephyrproject.org/2.5.0/guides/dts/intro.html#aliases-and-chosen-nodes) node named `zmk,kscan` which references the configured KSCAN driver (usually a GPIO matrix). For these keyboards, to be compatible with any Pro Micro compatible boards, the KSCAN configuration should reference the [nexus node](https://docs.zephyrproject.org/2.5.0/guides/porting/shields.html#gpio-nexus-nodes) that ZMK has standardized on. In particular, the `&pro_micro` aliases can be used to reference the standard digital pins of a Pro Micro for shields.
```

2021-08-03 02:47 UTC, Nicell commented on docs/docs/development/boards-shields-keymaps.md
> +  - A [chosen](https://docs.zephyrproject.org/2.5.0/guides/dts/intro.html#aliases-and-chosen-nodes) node named `zmk,kscan` which references the configured KSCAN driver (usually a GPIO matrix). For th
Added, thanks!

2021-09-26 02:40 UTC, petejohanson reviewed
Thoughts on how to prevent new shields getting merged in w/ the old names? Add an item to the check-list to make sure we're keeping an eye out for it?

2021-09-26 02:44 UTC, Nicell commented
> Thoughts on how to prevent new shields getting merged in w/ the old names? Add an item to the check-list to make sure we're keeping an eye out for it?

It doesn't look like there's a way to add a deprecation warning to our nexus nodes in DT, so no way to really detect usage. A check-list item seems like the best idea for now.

2021-09-26 03:08 UTC, petejohanson approved these changes
Thanks! This is much better.

2021-09-26 03:09 UTC, merged